added structure
nikolay-977/java-explore-with-me pull request #1
Opened 2022-11-14 19:47 UTC by nikolay-977

2022-11-24 18:51 UTC, Frilock requested changes
Добрый вечер, написал ряд комментариев к работе. Жду новую версию.

2022-11-24 18:51 UTC, Frilock commented on README.md
> +
Знаю, что по ТЗ у Вас сказано, чтобы в Readme файле была ссылка на проект. Предлагаю также в данном файле разместить информацию о самом проекте, за что каждый модуль отвечает, как проект собирается. Чтобы стороннему человеку который видит Ваш проект было проще. Кроме того, можно описать специфические конфиг файлы, если они есть. Это хорошая практика.

2022-11-24 18:51 UTC, Frilock commented on ewm-service/pom.xml
> +            <version>2.0.1.Final</version>
Общий комментарий по pom файлам. Смотрите, у Вас многомодульный проект, сейчас он состоит из 2х модулей, но возможно их будет больше. Так вот, хочется чтобы в приложении была одна точка добавления зависимостей. Такой обычно делают корневой pom файл. Там нужно сделать блок dependencyManager и добавлять те библиотеки которых нет в parent, а затем уже в других pom файлах подключать, но уже без указания версии. Кроме того, версии этих библиотек правильнее указывать в properties, поскольку pom файлы бывают довольно больших размеров и изменение версии может быть не такой простой задачей.

2022-11-24 18:51 UTC, Frilock commented on stats-server/src/main/java/ru/practicum/explorewithme/service/impl/StatsServiceImpl.java
> +            if (uris.isPresent()) {
Вообще такие конструкции можно заменить на конструкции с тернарным выражением:
listEndpoint = uris.isPresent() 
                    ? statsRepository.searchEndpointHitByUri(uris.get(), startDateTime, endDateTime)
                    : statsRepository.searchEndpointHit(startDateTime, endDateTime);
                    
 На мой взгляд, так более лаконично будет

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/resources/schema.sql
> +    name  VARCHAR(255)                            NOT NULL,
Смотрите, общий комментарий по скрипту и модели данных. Вы когда архитектуру БД планируете, нужно продумать размерность полей, то есть, например, поле код не должно иметь стандартный размер в 255, а его можно сделать, например, в 50 символов, а вот для описание нужно больше места, поэтому логичнее под данную колонку выделить, например, 1000. 
Кроме того, после того как Вы все указали в скрипте, тоже самое нужно сделать в аннотации Column для классов моделей. Указать размерность поля, а также дополнительные флаги, например, nullable = false.

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/impl/PublicEventsServiceImpl.java
> +            case "EVENT_DATE": {
Предлагаю данные варианты в enum вынести

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/impl/PublicEventsServiceImpl.java
> +                            .searchEventsByTextAndCategoriesAndPaidBySortByEventDay(text, categories, paid, parseDateTime(rangeStart), parseDateTime(rangeEnd), pageable);
Слишком длинная строка, аргументы переносите на другие строчки. Вообще я вроде Вам предлагал поставить sonarlint, по идее он показывает такие warnings

2022-11-24 18:51 UTC, Frilock commented on stats-server/src/main/java/ru/practicum/explorewithme/controller/StatsController.java
> +
Лишняя строчка

2022-11-24 18:51 UTC, Frilock commented on stats-server/src/main/java/ru/practicum/explorewithme/service/impl/StatsServiceImpl.java
> +@Slf4j
Не вижу использования логгера в данном классе. Либо уберите ее, либо логгируйте что то

2022-11-24 18:51 UTC, Frilock commented on stats-server/src/main/java/ru/practicum/explorewithme/controller/StatsController.java
> +@RequestMapping
По идее она не нужна если вы в аргументе ничего не указываете

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/controller/AdminEventsController.java
> +    @GetMapping()
Лишние скобки, проверьте в других местах тоже

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/controller/AdminUsersController.java
> +    @GetMapping()
Лишние скобки

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/exception/ErrorResponse.java
> +    private Integer status;
Давайте поле переименуем, оно как то в заблуждение вводит.

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/mapper/ParticipationRequestMapper.java
> +                .created(participationRequest.getCreated().format(FORMATTER))
А нам тут не нужно проверить, что participationRequest.getCreated() null не вернет?

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/model/Category.java
> +@Table(name = "categories", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
Когда смотрел на ваши скрипты заметил, что вы еще один constraint на многих таблицах делаете, а для чего это Вам? У Вас есть ключ id, зачем дополнительный ?

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/model/User.java
> +@EqualsAndHashCode
По идее у Вас Spring-data будьте аккуратней с генерацией hashCode и equals, там могут возникнуть проблемы

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/model/dto/NewUserRequest.java
> +    @NotNull
По моему одной Email достаточно

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/AdminEventsService.java
> +    List<EventFullDto> getEvents(List<Long> users, List<String> states, List<Long> categories, String rangeStart, String rangeEnd, Integer from, Integer size);
Слишком длинная строка, делайте переносы аргументов

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/PublicEventsService.java
> +    List<EventShortDto> getEvents(String text, List<Long> categories, Boolean paid, String rangeStart, String rangeEnd, Boolean onlyAvailable, String sort, Integer from, Integer size, HttpServletRequ
Слишком длинная строка, делайте перенос аргументов

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/impl/AdminCompilationsServiceImpl.java
> +                events.add(eventsRepository.findById(id).get());
Вот вопрос, у нас тут коллекция id по которой мы проходим и для каждой записи делаем findById. Нам что то мешает сделать вместо N запросов по id, сделать один по N id? Например, через in

Нужно очень внимательно следить за кол-вом запросов в БД, это действительно важно, где можно сделать 1 запрос вместо нескольких, лучше делать так.

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/impl/AdminEventsServiceImpl.java
> +        if (adminUpdateEventRequest.getAnnotation() != null) {
Данные ifы можно заменить на Optional.ofNullable(..).ifPresent(..); Будет гораздо компактнее

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/impl/AdminUsersServiceImpl.java
> +        if (ids.isEmpty()) {
Данную конструкцию можно заменить на тернарное выражение, будет выглядеть компактнее.

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/impl/PrivateUserRequestsServiceImpl.java
> +
Лишний пропуск строки

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/impl/PrivateUserRequestsServiceImpl.java
> +
Лишний пропуск строки

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/impl/PublicCompilationsServiceImpl.java
> +        List<Compilation> compilationList;
Данную конструкцию можно заменить на тернарное выражение, будет выглядеть компактнее.

2022-11-24 18:51 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/repository/EventsRepository.java
> +public interface EventsRepository extends JpaRepository<Event, Long> {
Знаю, что в ТЗ у Вас это было задание со звездочкой, но вообще в такой большой работе, хочется увидеть unit тесты, которые тестируют хотя бы сервисы, поскольку это поможет Вам отловить возможные ошибки, а сама работа будет выглядеть солиднее

2022-11-27 11:06 UTC, nikolay-977 commented on README.md
> +
Исправлено

2022-11-27 11:06 UTC, nikolay-977 commented on ewm-service/pom.xml
> +            <version>2.0.1.Final</version>
Исправлено

2022-11-27 11:07 UTC, nikolay-977 commented on stats-server/src/main/java/ru/practicum/explorewithme/service/impl/StatsServiceImpl.java
> +            if (uris.isPresent()) {
Исправлено

2022-11-27 11:14 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/impl/PublicEventsServiceImpl.java
> +            case "EVENT_DATE": {
Исправлено

2022-11-27 11:30 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/impl/AdminUsersServiceImpl.java
> +        if (ids.isEmpty()) {
исправлено

2022-11-27 11:30 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/impl/PrivateUserRequestsServiceImpl.java
> +
исправлено

2022-11-27 11:32 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/impl/PublicCompilationsServiceImpl.java
> +        List<Compilation> compilationList;
исправлено

2022-11-27 11:44 UTC, nikolay-977 commented on ewm-service/src/main/resources/schema.sql
> +    name  VARCHAR(255)                            NOT NULL,
исправлено

2022-11-27 13:38 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/repository/EventsRepository.java
> +public interface EventsRepository extends JpaRepository<Event, Long> {
Согласен, но к сожалению не успеваю по времени, но обязательно добавлю в будущем

2022-11-27 17:05 UTC, Frilock requested changes
Добрый день, такое чувство Вы не увидели вложенные комментарии. Там есть раскрыть то еще 15 комментариев есть. По крайней мере Вы мне на них не ответили

2022-11-27 18:07 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/impl/PublicEventsServiceImpl.java
> +                            .searchEventsByTextAndCategoriesAndPaidBySortByEventDay(text, categories, paid, parseDateTime(rangeStart), parseDateTime(rangeEnd), pageable);
Исправлено

2022-11-27 18:07 UTC, nikolay-977 commented on stats-server/src/main/java/ru/practicum/explorewithme/controller/StatsController.java
> +
исправлено

2022-11-27 18:07 UTC, nikolay-977 commented on stats-server/src/main/java/ru/practicum/explorewithme/service/impl/StatsServiceImpl.java
> +@Slf4j
исправлено

2022-11-27 18:07 UTC, nikolay-977 commented on stats-server/src/main/java/ru/practicum/explorewithme/controller/StatsController.java
> +@RequestMapping
исправлено

2022-11-27 18:08 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/controller/AdminEventsController.java
> +    @GetMapping()
исправлено

2022-11-27 18:08 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/controller/AdminUsersController.java
> +    @GetMapping()
исправлено

2022-11-27 18:08 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/exception/ErrorResponse.java
> +    private Integer status;
исправлено

2022-11-27 18:10 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/model/dto/NewUserRequest.java
> +    @NotNull
исправлено

2022-11-27 18:12 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/AdminEventsService.java
> +    List<EventFullDto> getEvents(List<Long> users, List<String> states, List<Long> categories, String rangeStart, String rangeEnd, Integer from, Integer size);
Исправлено

2022-11-27 18:14 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/PublicEventsService.java
> +    List<EventShortDto> getEvents(String text, List<Long> categories, Boolean paid, String rangeStart, String rangeEnd, Boolean onlyAvailable, String sort, Integer from, Integer size, HttpServletRequ
исправлено

2022-11-27 18:27 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/impl/AdminEventsServiceImpl.java
> +        if (adminUpdateEventRequest.getAnnotation() != null) {
исправлено

2022-11-27 18:28 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/impl/PrivateUserRequestsServiceImpl.java
> +
исправлено

2022-11-27 18:30 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/model/Category.java
> +@Table(name = "categories", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
исправил

2022-11-27 18:33 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/mapper/ParticipationRequestMapper.java
> +                .created(participationRequest.getCreated().format(FORMATTER))
исправил

2022-11-27 18:51 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/service/impl/AdminCompilationsServiceImpl.java
> +                events.add(eventsRepository.findById(id).get());
исправлено

2022-11-27 18:51 UTC, nikolay-977 commented on ewm-service/src/main/java/ru/practicum/explorewithme/model/User.java
> +@EqualsAndHashCode
@EqualsAndHashCode убрал, т.к. он не используется в работе

2022-11-28 08:03 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/explorewithme/model/User.java
> +@EqualsAndHashCode
https://habr.com/ru/company/haulmont/blog/564682/

2022-11-28 08:04 UTC, Frilock approved these changes
Принято, успехов в дальнейшей работе.

2022-11-28 20:28 UTC, merged